import type {
  AuditEntry,
  ClassGroupDetail,
  ClassGroupRow,
  CourseRow,
  DashboardMetrics,
  DocumentDelivery,
  DocumentItem,
  EnrollmentHistoryItem,
  PaymentMethod,
  ReviewFlag,
  ReviewQueueItem,
  SeatWatchItem,
  StaffUser,
  StudentDetail,
  StudentRow,
} from './types'

/**
 * Mock backoffice dataset for the UI/UX phase. Every value is shaped like the
 * database row it will replace (CLAUDE.md §5); swapping this module for real
 * API calls should not require touching a component.
 *
 * Prices are the honest per-course prices (e.g. Inglés S/69.90) — never a
 * discount, never the S/1 landing hook. Dates are UTC, rendered in
 * America/Lima. Names are fictional.
 */

/** Signed-in staff member driving the mocked session. */
export function getStaffSession(): StaffUser {
  return {
    id: 'staff_01',
    firstName: 'Lucía',
    lastName: 'Ramírez',
    email: 'lucia.ramirez@onlyonecoin.edu.pe',
    role: 'admin',
  }
}

const PERIOD = 'Ciclo 2026-II'

function enrollment(
  partial: Partial<EnrollmentHistoryItem> & Pick<EnrollmentHistoryItem, 'id'>,
): EnrollmentHistoryItem {
  return {
    status: 'active',
    seatStatus: 'confirmed',
    createdAt: '2026-07-02T14:20:00Z',
    courseName: 'Inglés Básico A1',
    classGroupName: 'A1 — Lun/Mié 18:00',
    teacherName: 'Carlos Meza',
    modality: 'online',
    academicPeriodName: PERIOD,
    planName: 'Paquete completo',
    planPriceId: 'pp_en_a1_v3',
    amountCents: 6990,
    currency: 'PEN',
    paymentStatus: 'approved',
    paymentMethod: 'yape',
    operationNumber: '00871245',
    paidAt: '2026-07-02T14:12:00Z',
    progressPct: 45,
    ...partial,
  }
}

function audit(
  partial: Partial<AuditEntry> & Pick<AuditEntry, 'id' | 'action' | 'at'>,
): AuditEntry {
  return {
    actorName: 'Lucía Ramírez',
    actorRole: 'admin',
    reference: null,
    ...partial,
  }
}

/**
 * Fee for the constancia de matrícula (`docs/REGRAS-NEGOCIO.md` §5: S/25).
 * A backoffice setting in the real system, never a constant in the code — the
 * same rule the payment tolerance follows (CLAUDE.md §5).
 */
export const CONSTANCIA_FEE_CENTS = 2500

/**
 * Minimum passing grade, 0–20 scale (`docs/REGRAS-NEGOCIO.md` §3: 14). Also a
 * backoffice setting later; it lives here so the batch preview has one source.
 */
export const PASSING_GRADE = 14

function noEmail(): DocumentDelivery {
  return { status: 'not_sent', lastSentAt: null, attempts: 0 }
}

function doc(
  partial: Partial<DocumentItem> &
    Pick<DocumentItem, 'id' | 'type' | 'enrollmentId'>,
): DocumentItem {
  return {
    status: 'available',
    issuedAt: null,
    verificationCode: null,
    issuedByName: null,
    delivery: noEmail(),
    ...partial,
  }
}

/**
 * The tail of the human review queue. One entry describes a person, the seat
 * they reserved and the receipt still waiting on a human — the student file
 * and the queue row are both derived from it, so the two screens can never
 * disagree about the same receipt.
 */
interface PendingReceipt {
  id: string
  studentId: string
  firstName: string
  lastName: string
  nationalId: string
  email: string
  phone: string
  region: string
  city: string
  birthDate: string
  courseName: string
  classGroupName: string
  teacherName: string
  method: PaymentMethod
  /** What the extraction read on the receipt. */
  amountCents: number
  /** The frozen plan price it is checked against (CLAUDE.md §5). */
  expectedAmountCents: number
  operationNumber: string | null
  flag: ReviewFlag
  tier: number
  confidence: number
  submittedAt: string
}

/** Price version each course was selling under this period. */
const PLAN_PRICE_ID: Record<string, string> = {
  'Inglés Básico A1': 'pp_en_a1_v3',
  'Inglés Intermedio B1': 'pp_en_b1_v2',
  'Francés Inicial': 'pp_fr_i_v2',
  'Alemán Inicial': 'pp_de_i_v1',
  'Italiano Inicial': 'pp_it_i_v1',
  'Portugués Inicial': 'pp_pt_i_v2',
  'Quechua Conversacional': 'pp_qu_i_v1',
}

const pendingReceipts: PendingReceipt[] = [
  {
    id: 'rev_06',
    studentId: 'stu_0009',
    firstName: 'Rosa Elena',
    lastName: 'Ccahuana Mamani',
    nationalId: '72880145',
    email: 'rosa.ccahuana@gmail.com',
    phone: '+51 984 220 118',
    region: 'Cusco',
    city: 'Cusco',
    birthDate: '2003-02-11',
    courseName: 'Quechua Conversacional',
    classGroupName: 'QU-I — Sáb 11:00',
    teacherName: 'Rosa Ccahuana',
    method: 'yape',
    amountCents: 5490,
    expectedAmountCents: 5490,
    operationNumber: '77310021',
    flag: 'low_confidence',
    tier: 2,
    confidence: 0.58,
    submittedAt: '2026-08-17T14:20:00Z',
  },
  {
    id: 'rev_07',
    studentId: 'stu_0010',
    firstName: 'Luis Enrique',
    lastName: 'Vargas Ríos',
    nationalId: '70114892',
    email: 'luis.vargas@outlook.com',
    phone: '+51 958 771 204',
    region: 'Arequipa',
    city: 'Arequipa',
    birthDate: '2001-07-23',
    courseName: 'Inglés Intermedio B1',
    classGroupName: 'B1 — Mar/Jue 19:00',
    teacherName: 'Carlos Meza',
    method: 'plin',
    amountCents: 7990,
    expectedAmountCents: 7990,
    operationNumber: null,
    flag: 'illegible',
    tier: 3,
    confidence: 0.29,
    submittedAt: '2026-08-17T16:05:00Z',
  },
  {
    id: 'rev_08',
    studentId: 'stu_0011',
    firstName: 'Fiorella',
    lastName: 'Ramos Aguilar',
    nationalId: '75620338',
    email: 'fiorella.ramos@gmail.com',
    phone: '+51 987 445 019',
    region: 'Lima',
    city: 'Lima',
    birthDate: '2005-05-09',
    courseName: 'Italiano Inicial',
    classGroupName: 'IT-I — Lun/Mié 20:00',
    teacherName: 'Paola Benítez',
    method: 'bcp',
    amountCents: 6390,
    expectedAmountCents: 6490,
    operationNumber: '00845127',
    flag: 'amount_mismatch',
    tier: 2,
    confidence: 0.74,
    submittedAt: '2026-08-17T18:40:00Z',
  },
  {
    id: 'rev_09',
    studentId: 'stu_0012',
    firstName: 'Álvaro',
    lastName: 'Quispe Huanca',
    nationalId: '71903255',
    email: 'alvaro.quispe@gmail.com',
    phone: '+51 951 660 782',
    region: 'Puno',
    city: 'Juliaca',
    birthDate: '2004-09-17',
    courseName: 'Inglés Básico A1',
    classGroupName: 'A1 — Sáb 09:00',
    teacherName: 'Carlos Meza',
    method: 'yape',
    amountCents: 6990,
    expectedAmountCents: 6990,
    operationNumber: '00993588',
    flag: 'model_divergence',
    tier: 2,
    confidence: 0.52,
    submittedAt: '2026-08-17T21:10:00Z',
  },
  {
    id: 'rev_10',
    studentId: 'stu_0013',
    firstName: 'Milagros',
    lastName: 'Paredes Chávez',
    nationalId: '74558012',
    email: 'milagros.paredes@gmail.com',
    phone: '+51 944 302 551',
    region: 'La Libertad',
    city: 'Trujillo',
    birthDate: '2002-12-01',
    courseName: 'Francés Inicial',
    classGroupName: 'FR-I — Sáb 15:00',
    teacherName: 'Marion Lefèvre',
    method: 'interbank',
    amountCents: 6490,
    expectedAmountCents: 6490,
    operationNumber: '31220745',
    flag: 'low_confidence',
    tier: 2,
    confidence: 0.63,
    submittedAt: '2026-08-18T00:35:00Z',
  },
  {
    id: 'rev_11',
    studentId: 'stu_0014',
    firstName: 'Kevin Anthony',
    lastName: 'Salazar Loayza',
    nationalId: '73104778',
    email: 'kevin.salazar@outlook.com',
    phone: '+51 964 118 330',
    region: 'Junín',
    city: 'Huancayo',
    birthDate: '2000-03-28',
    courseName: 'Portugués Inicial',
    classGroupName: 'PT-I — Mar/Jue 18:00',
    teacherName: 'Bruno Antunes',
    method: 'yape',
    amountCents: 5990,
    expectedAmountCents: 5990,
    operationNumber: '00611233',
    flag: 'duplicate_phash',
    tier: 0,
    confidence: 0.97,
    submittedAt: '2026-08-18T02:15:00Z',
  },
  {
    id: 'rev_12',
    studentId: 'stu_0015',
    firstName: 'Andrea Sofía',
    lastName: 'Ticona Flores',
    nationalId: '76220901',
    email: 'andrea.ticona@gmail.com',
    phone: '+51 952 887 140',
    region: 'Tacna',
    city: 'Tacna',
    birthDate: '2006-08-14',
    courseName: 'Alemán Inicial',
    classGroupName: 'DE-I — Lun/Mié 19:00',
    teacherName: 'Klaus Brenner',
    method: 'plin',
    amountCents: 6890,
    expectedAmountCents: 6990,
    operationNumber: '61330427',
    flag: 'amount_mismatch',
    tier: 2,
    confidence: 0.69,
    submittedAt: '2026-08-18T11:48:00Z',
  },
  {
    id: 'rev_13',
    studentId: 'stu_0016',
    firstName: 'Jorge Luis',
    lastName: 'Ñahui Bautista',
    nationalId: '70882134',
    email: 'jorge.nahui@gmail.com',
    phone: '+51 966 220 517',
    region: 'Ayacucho',
    city: 'Huamanga',
    birthDate: '1999-11-05',
    courseName: 'Quechua Conversacional',
    classGroupName: 'QU-I — Sáb 11:00',
    teacherName: 'Rosa Ccahuana',
    method: 'bcp',
    amountCents: 5490,
    expectedAmountCents: 5490,
    operationNumber: null,
    flag: 'illegible',
    tier: 3,
    confidence: 0.31,
    submittedAt: '2026-08-18T13:05:00Z',
  },
  {
    id: 'rev_14',
    studentId: 'stu_0017',
    firstName: 'Nayeli',
    lastName: 'Condori Apaza',
    nationalId: '75440672',
    email: 'nayeli.condori@gmail.com',
    phone: '+51 951 003 224',
    region: 'Puno',
    city: 'Juliaca',
    birthDate: '2005-01-19',
    courseName: 'Inglés Básico A1',
    classGroupName: 'A1 — Lun/Mié 18:00',
    teacherName: 'Carlos Meza',
    method: 'yape',
    amountCents: 6990,
    expectedAmountCents: 6990,
    operationNumber: '00994102',
    flag: 'low_confidence',
    tier: 2,
    confidence: 0.66,
    submittedAt: '2026-08-18T14:30:00Z',
  },
  {
    id: 'rev_15',
    studentId: 'stu_0018',
    firstName: 'Piero Alessandro',
    lastName: 'Gutiérrez Nieto',
    nationalId: '72015883',
    email: 'piero.gutierrez@outlook.com',
    phone: '+51 987 660 471',
    region: 'Callao',
    city: 'Callao',
    birthDate: '2003-06-30',
    courseName: 'Italiano Inicial',
    classGroupName: 'IT-I — Mar/Jue 19:00',
    teacherName: 'Paolo Grimaldi',
    method: 'plin',
    amountCents: 6490,
    expectedAmountCents: 6490,
    operationNumber: '61441209',
    flag: 'model_divergence',
    tier: 2,
    confidence: 0.49,
    submittedAt: '2026-08-18T15:22:00Z',
  },
  {
    id: 'rev_16',
    studentId: 'stu_0019',
    firstName: 'Brenda Yaneth',
    lastName: 'Castillo Rojas',
    nationalId: '74772360',
    email: 'brenda.castillo@gmail.com',
    phone: '+51 969 114 802',
    region: 'Piura',
    city: 'Piura',
    birthDate: '2001-04-08',
    courseName: 'Inglés Intermedio B1',
    classGroupName: 'B1 — Lun/Mié 20:00',
    teacherName: 'Andrea Solís',
    method: 'yape',
    amountCents: 7890,
    expectedAmountCents: 7990,
    operationNumber: '00995771',
    flag: 'amount_mismatch',
    tier: 2,
    confidence: 0.72,
    submittedAt: '2026-08-18T17:44:00Z',
  },
  {
    id: 'rev_17',
    studentId: 'stu_0020',
    firstName: 'Marco Antonio',
    lastName: 'Zeballos Pinto',
    nationalId: '70338914',
    email: 'marco.zeballos@gmail.com',
    phone: '+51 958 220 660',
    region: 'Arequipa',
    city: 'Arequipa',
    birthDate: '1998-10-22',
    courseName: 'Alemán Inicial',
    classGroupName: 'DE-I — Sáb 10:00',
    teacherName: 'Katrin Wolf',
    method: 'interbank',
    amountCents: 6990,
    expectedAmountCents: 6990,
    operationNumber: '31441088',
    flag: 'duplicate_phash',
    tier: 0,
    confidence: 0.99,
    submittedAt: '2026-08-18T19:10:00Z',
  },
  {
    id: 'rev_18',
    studentId: 'stu_0021',
    firstName: 'Lucero',
    lastName: 'Huamaní Quispe',
    nationalId: '76110458',
    email: 'lucero.huamani@gmail.com',
    phone: '+51 984 771 336',
    region: 'Cusco',
    city: 'Cusco',
    birthDate: '2004-02-27',
    courseName: 'Francés Inicial',
    classGroupName: 'FR-I — Mar/Jue 18:00',
    teacherName: 'Claire Dubois',
    method: 'yape',
    amountCents: 6490,
    expectedAmountCents: 6490,
    operationNumber: '00996314',
    flag: 'low_confidence',
    tier: 2,
    confidence: 0.61,
    submittedAt: '2026-08-18T20:05:00Z',
  },
  {
    id: 'rev_19',
    studentId: 'stu_0022',
    firstName: 'Christian Paolo',
    lastName: 'Mendoza Vela',
    nationalId: '71660207',
    email: 'christian.mendoza@outlook.com',
    phone: '+51 965 447 128',
    region: 'Loreto',
    city: 'Iquitos',
    birthDate: '2000-07-16',
    courseName: 'Portugués Inicial',
    classGroupName: 'PT-I — Sáb 09:00',
    teacherName: 'Ana Beltrán',
    method: 'plin',
    amountCents: 5890,
    expectedAmountCents: 5990,
    operationNumber: '61552044',
    flag: 'amount_mismatch',
    tier: 2,
    confidence: 0.7,
    submittedAt: '2026-08-18T22:31:00Z',
  },
  {
    id: 'rev_20',
    studentId: 'stu_0023',
    firstName: 'Ariana Belén',
    lastName: 'Ramírez Soto',
    nationalId: '75908341',
    email: 'ariana.ramirez@gmail.com',
    phone: '+51 987 220 905',
    region: 'Lima',
    city: 'Lima',
    birthDate: '2006-11-11',
    courseName: 'Inglés Básico A1',
    classGroupName: 'A1 — Mar/Jue 20:00',
    teacherName: 'Carlos Meza',
    method: 'bcp',
    amountCents: 6990,
    expectedAmountCents: 6990,
    operationNumber: null,
    flag: 'illegible',
    tier: 3,
    confidence: 0.27,
    submittedAt: '2026-08-19T01:12:00Z',
  },
  {
    id: 'rev_21',
    studentId: 'stu_0024',
    firstName: 'Renato',
    lastName: 'Aliaga Espinoza',
    nationalId: '73220617',
    email: 'renato.aliaga@gmail.com',
    phone: '+51 943 118 770',
    region: 'Áncash',
    city: 'Huaraz',
    birthDate: '2002-05-03',
    courseName: 'Quechua Conversacional',
    classGroupName: 'QU-I — Mar/Jue 19:00',
    teacherName: 'Nilda Puma',
    method: 'yape',
    amountCents: 5490,
    expectedAmountCents: 5490,
    operationNumber: '00997220',
    flag: 'model_divergence',
    tier: 2,
    confidence: 0.54,
    submittedAt: '2026-08-19T03:40:00Z',
  },
  {
    id: 'rev_22',
    studentId: 'stu_0025',
    firstName: 'Diana Carolina',
    lastName: 'Peralta Ruiz',
    nationalId: '74003185',
    email: 'diana.peralta@gmail.com',
    phone: '+51 976 550 214',
    region: 'Cajamarca',
    city: 'Cajamarca',
    birthDate: '2005-09-21',
    courseName: 'Inglés Básico A1',
    classGroupName: 'A1 — Sáb 09:00',
    teacherName: 'Carlos Meza',
    method: 'yape',
    amountCents: 6990,
    expectedAmountCents: 6990,
    operationNumber: '00997845',
    flag: 'low_confidence',
    tier: 2,
    confidence: 0.64,
    submittedAt: '2026-08-19T04:55:00Z',
  },
  {
    id: 'rev_23',
    studentId: 'stu_0026',
    firstName: 'Gabriel Ismael',
    lastName: 'Torres Ancajima',
    nationalId: '72447039',
    email: 'gabriel.torres@outlook.com',
    phone: '+51 969 880 143',
    region: 'Piura',
    city: 'Sullana',
    birthDate: '1997-12-09',
    courseName: 'Italiano Inicial',
    classGroupName: 'IT-I — Lun/Mié 20:00',
    teacherName: 'Paola Benítez',
    method: 'plin',
    amountCents: 6490,
    expectedAmountCents: 6490,
    operationNumber: '61663902',
    flag: 'duplicate_phash',
    tier: 0,
    confidence: 0.96,
    submittedAt: '2026-08-19T06:20:00Z',
  },
]

/**
 * A student the panel only knows because a receipt of theirs is waiting: seat
 * reserved, payment under review, nothing issued yet.
 */
function pendingStudent(receipt: PendingReceipt): StudentDetail {
  return {
    id: receipt.studentId,
    firstName: receipt.firstName,
    lastName: receipt.lastName,
    nationalIdType: 'DNI',
    nationalId: receipt.nationalId,
    email: receipt.email,
    phone: receipt.phone,
    birthDate: receipt.birthDate,
    isMinor: false,
    status: 'under_review',
    country: 'PE',
    region: receipt.region,
    city: receipt.city,
    activeCourses: 0,
    totalEnrollments: 1,
    createdAt: receipt.submittedAt,
    lastActivityAt: receipt.submittedAt,
    guardian: null,
    enrollments: [
      enrollment({
        id: receipt.id.replace('rev_', 'enr_19'),
        status: 'under_review',
        seatStatus: 'reserved',
        paymentStatus: 'under_review',
        courseName: receipt.courseName,
        classGroupName: receipt.classGroupName,
        teacherName: receipt.teacherName,
        planPriceId: PLAN_PRICE_ID[receipt.courseName] ?? 'pp_en_a1_v3',
        // The enrollment carries the frozen plan price; what the receipt reads
        // is the extraction's problem, not the enrollment's (CLAUDE.md §5).
        amountCents: receipt.expectedAmountCents,
        paymentMethod: receipt.method,
        operationNumber: receipt.operationNumber,
        createdAt: receipt.submittedAt,
        paidAt: null,
        progressPct: null,
      }),
    ],
    documents: [],
    documentRequests: [],
    attachments: [],
    activity: [
      audit({
        id: `aud_${receipt.id}_flagged`,
        action: 'payment_flagged',
        at: receipt.submittedAt,
        actorName: 'Sistema',
        actorRole: 'mass_approver',
        reference: { kind: 'review_flag', flag: receipt.flag },
      }),
      audit({
        id: `aud_${receipt.id}_created`,
        action: 'enrollment_created',
        at: receipt.submittedAt,
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: { kind: 'course', name: receipt.courseName },
      }),
    ],
  }
}

const students: StudentDetail[] = [
  {
    id: 'stu_0001',
    firstName: 'María Fernanda',
    lastName: 'Quispe Ramos',
    nationalIdType: 'DNI',
    nationalId: '72814905',
    email: 'mariafernanda.quispe@gmail.com',
    phone: '+51 987 654 321',
    birthDate: '2010-03-18',
    isMinor: true,
    status: 'active',
    country: 'PE',
    region: 'Cusco',
    city: 'Cusco',
    activeCourses: 2,
    totalEnrollments: 3,
    createdAt: '2026-02-11T15:04:00Z',
    lastActivityAt: '2026-08-17T23:10:00Z',
    guardian: {
      firstName: 'Rosa',
      lastName: 'Ramos Huamán',
      relationship: 'mother',
      nationalIdType: 'DNI',
      nationalId: '41209877',
      email: 'rosa.ramos@gmail.com',
      phone: '+51 984 112 700',
      consent: {
        version: 'v2026-01',
        acceptedAt: '2026-02-11T15:04:00Z',
        ip: '190.234.11.42',
      },
    },
    enrollments: [
      enrollment({ id: 'enr_1001' }),
      enrollment({
        id: 'enr_1002',
        courseName: 'Portugués Inicial',
        classGroupName: 'PT-I — Sáb 09:00',
        teacherName: 'Ana Beltrán',
        planPriceId: 'pp_pt_i_v2',
        amountCents: 5990,
        paymentMethod: 'plin',
        operationNumber: '55120398',
        createdAt: '2026-07-28T16:40:00Z',
        paidAt: '2026-07-28T16:31:00Z',
        progressPct: 12,
      }),
      enrollment({
        id: 'enr_0930',
        status: 'completed',
        courseName: 'Inglés Introductorio',
        classGroupName: 'INT — Mar/Jue 19:00',
        academicPeriodName: 'Ciclo 2026-I',
        planPriceId: 'pp_en_int_v1',
        amountCents: 4990,
        createdAt: '2026-02-11T15:04:00Z',
        paidAt: '2026-02-11T14:58:00Z',
        operationNumber: '00412907',
        progressPct: 100,
      }),
    ],
    documents: [
      doc({
        id: 'doc_1',
        type: 'enrollment_certificate',
        enrollmentId: 'enr_1001',
        issuedAt: '2026-07-03T12:00:00Z',
        verificationCode: 'OOC-2026-K4M7QP',
        issuedByName: 'Lucía Ramírez',
        delivery: { status: 'sent', lastSentAt: '2026-07-03T12:01:00Z', attempts: 1 },
      }),
      doc({
        id: 'doc_2',
        type: 'certificate',
        enrollmentId: 'enr_0930',
        issuedAt: '2026-06-30T12:00:00Z',
        verificationCode: 'OOC-2026-B92XR5',
        delivery: { status: 'sent', lastSentAt: '2026-06-30T12:02:00Z', attempts: 1 },
      }),
      doc({
        id: 'doc_3',
        type: 'certificate',
        status: 'locked',
        enrollmentId: 'enr_1001',
      }),
    ],
    documentRequests: [
      {
        id: 'dreq_1',
        type: 'enrollment_certificate',
        enrollmentId: 'enr_1001',
        requestedAt: '2026-08-18T15:40:00Z',
        feeCents: CONSTANCIA_FEE_CENTS,
        currency: 'PEN',
        paymentStatus: 'under_review',
        paymentMethod: 'yape',
        operationNumber: '00918744',
      },
    ],
    attachments: [
      {
        id: 'att_1',
        kind: 'guardian_consent',
        fileName: 'consentimiento-apoderado-firmado.pdf',
        sizeBytes: 412_336,
        uploadedAt: '2026-07-02T15:10:00Z',
        uploadedBy: 'student',
        uploadedByName: 'María Fernanda Quispe Ramos',
      },
      {
        id: 'att_2',
        kind: 'national_id',
        fileName: 'dni-72814905.jpg',
        sizeBytes: 1_204_880,
        uploadedAt: '2026-07-02T15:08:00Z',
        uploadedBy: 'student',
        uploadedByName: 'María Fernanda Quispe Ramos',
      },
    ],
    activity: [
      audit({
        id: 'aud_9',
        action: 'enrollment_created',
        at: '2026-07-28T16:40:00Z',
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: { kind: 'course', name: 'Portugués Inicial' },
      }),
      audit({
        id: 'aud_8',
        action: 'payment_approved',
        at: '2026-07-28T16:44:00Z',
        actorName: 'Diego Salas',
        actorRole: 'treasury',
        reference: { kind: 'operation', number: '55120398' },
      }),
      audit({
        id: 'aud_7',
        action: 'document_issued',
        at: '2026-06-30T12:00:00Z',
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: { kind: 'course', name: 'Inglés Introductorio' },
      }),
      audit({
        id: 'aud_6',
        action: 'student_updated',
        at: '2026-05-14T18:22:00Z',
        reference: { kind: 'student_field', field: 'phone' },
      }),
      audit({
        id: 'aud_5',
        action: 'credentials_sent',
        at: '2026-02-11T15:10:00Z',
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: null,
      }),
      audit({
        id: 'aud_4',
        action: 'student_created',
        at: '2026-02-11T15:04:00Z',
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: null,
      }),
    ],
  },
  {
    id: 'stu_0002',
    firstName: 'Jhon Alexander',
    lastName: 'Mamani Ccama',
    nationalIdType: 'DNI',
    nationalId: '70551238',
    email: 'jhon.mamani@outlook.com',
    phone: '+51 951 220 447',
    birthDate: '2004-11-02',
    isMinor: false,
    status: 'under_review',
    country: 'PE',
    region: 'Puno',
    city: 'Puno',
    activeCourses: 0,
    totalEnrollments: 1,
    createdAt: '2026-08-18T21:02:00Z',
    lastActivityAt: '2026-08-18T21:02:00Z',
    guardian: null,
    enrollments: [
      enrollment({
        id: 'enr_1188',
        status: 'under_review',
        seatStatus: 'reserved',
        paymentStatus: 'under_review',
        courseName: 'Inglés Básico A1',
        classGroupName: 'A1 — Mar/Jue 20:00',
        teacherName: 'Carlos Meza',
        createdAt: '2026-08-18T21:02:00Z',
        paidAt: null,
        operationNumber: '00993412',
        progressPct: null,
      }),
    ],
    documents: [],
    documentRequests: [],
    attachments: [],
    activity: [
      audit({
        id: 'aud_21',
        action: 'payment_flagged',
        at: '2026-08-18T21:03:00Z',
        actorName: 'Sistema',
        actorRole: 'mass_approver',
        reference: { kind: 'review_flag', flag: 'amount_mismatch' },
      }),
      audit({
        id: 'aud_20',
        action: 'enrollment_created',
        at: '2026-08-18T21:02:00Z',
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: { kind: 'course', name: 'Inglés Básico A1' },
      }),
    ],
  },
  {
    id: 'stu_0003',
    firstName: 'Camila',
    lastName: 'Torres Vílchez',
    nationalIdType: 'DNI',
    nationalId: '75320981',
    email: 'camila.torres@gmail.com',
    phone: '+51 976 334 128',
    birthDate: '2008-06-24',
    isMinor: true,
    status: 'active',
    country: 'PE',
    region: 'La Libertad',
    city: 'Trujillo',
    activeCourses: 1,
    totalEnrollments: 2,
    createdAt: '2026-03-05T13:30:00Z',
    lastActivityAt: '2026-08-15T01:12:00Z',
    guardian: {
      firstName: 'Manuel',
      lastName: 'Torres Aguilar',
      relationship: 'father',
      nationalIdType: 'DNI',
      nationalId: '40118266',
      email: 'manuel.torres@gmail.com',
      phone: '+51 976 334 100',
      consent: null,
    },
    enrollments: [
      enrollment({
        id: 'enr_1120',
        courseName: 'Quechua Conversacional',
        classGroupName: 'QU-I — Sáb 11:00',
        teacherName: 'Nilda Puma',
        modality: 'in_person',
        planPriceId: 'pp_qu_i_v1',
        amountCents: 5490,
        paymentMethod: 'bcp',
        operationNumber: '77120054',
        createdAt: '2026-07-19T11:05:00Z',
        paidAt: '2026-07-19T10:58:00Z',
        progressPct: 30,
      }),
      enrollment({
        id: 'enr_1005',
        status: 'completed',
        academicPeriodName: 'Ciclo 2026-I',
        createdAt: '2026-03-05T13:30:00Z',
        paidAt: '2026-03-05T13:22:00Z',
        operationNumber: '00522118',
        progressPct: 100,
      }),
    ],
    documents: [
      doc({
        id: 'doc_11',
        type: 'enrollment_certificate',
        enrollmentId: 'enr_1120',
        issuedAt: '2026-07-20T12:00:00Z',
        verificationCode: 'OOC-2026-T61HN8',
        issuedByName: 'Lucía Ramírez',
        // Bounced: the address is full, the classic Gmail-sin-espacio case.
        delivery: { status: 'failed', lastSentAt: '2026-07-20T12:01:00Z', attempts: 2 },
      }),
    ],
    documentRequests: [],
    attachments: [],
    activity: [
      audit({
        id: 'aud_31',
        action: 'email_sent',
        at: '2026-08-15T01:12:00Z',
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: { kind: 'email_template', template: 'guardian_consent_reminder' },
      }),
      audit({
        id: 'aud_30',
        action: 'payment_approved',
        at: '2026-07-19T11:09:00Z',
        actorName: 'Diego Salas',
        actorRole: 'treasury',
        reference: { kind: 'operation', number: '77120054' },
      }),
    ],
  },
  {
    id: 'stu_0004',
    firstName: 'Sebastián',
    lastName: 'Ríos Paredes',
    nationalIdType: 'CE',
    nationalId: '001234567',
    email: 'sebastian.rios@gmail.com',
    phone: '+51 933 887 012',
    birthDate: '1998-01-09',
    isMinor: false,
    status: 'inactive',
    country: 'PE',
    region: 'Lima',
    city: 'Lima',
    activeCourses: 0,
    totalEnrollments: 1,
    createdAt: '2025-09-14T17:45:00Z',
    lastActivityAt: '2026-01-20T14:00:00Z',
    guardian: null,
    enrollments: [
      enrollment({
        id: 'enr_0712',
        status: 'completed',
        academicPeriodName: 'Ciclo 2025-II',
        courseName: 'Italiano Inicial',
        classGroupName: 'IT-I — Lun/Mié 20:00',
        teacherName: 'Paolo Grimaldi',
        planPriceId: 'pp_it_i_v1',
        amountCents: 6490,
        paymentMethod: 'interbank',
        operationNumber: '31882004',
        createdAt: '2025-09-14T17:45:00Z',
        paidAt: '2025-09-14T17:33:00Z',
        progressPct: 100,
      }),
    ],
    documents: [
      doc({
        id: 'doc_21',
        type: 'certificate',
        enrollmentId: 'enr_0712',
        issuedAt: '2026-01-20T14:00:00Z',
        verificationCode: 'OOC-2026-D33WLA',
        delivery: { status: 'sent', lastSentAt: '2026-01-20T14:03:00Z', attempts: 1 },
      }),
    ],
    documentRequests: [],
    attachments: [],
    activity: [
      audit({
        id: 'aud_41',
        action: 'document_issued',
        at: '2026-01-20T14:00:00Z',
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: { kind: 'course', name: 'Italiano Inicial' },
      }),
    ],
  },
  {
    id: 'stu_0005',
    firstName: 'Ana Lucía',
    lastName: 'Chávez Soto',
    nationalIdType: 'DNI',
    nationalId: '73998120',
    email: 'analucia.chavez@gmail.com',
    phone: '+51 942 118 903',
    birthDate: '2011-09-30',
    isMinor: true,
    status: 'under_review',
    country: 'PE',
    region: 'Arequipa',
    city: 'Arequipa',
    activeCourses: 0,
    totalEnrollments: 1,
    createdAt: '2026-08-19T02:15:00Z',
    lastActivityAt: '2026-08-19T02:15:00Z',
    guardian: {
      firstName: 'Elena',
      lastName: 'Soto Vargas',
      relationship: 'mother',
      nationalIdType: 'DNI',
      nationalId: '42887301',
      email: 'elena.soto@gmail.com',
      phone: '+51 942 118 900',
      consent: {
        version: 'v2026-01',
        acceptedAt: '2026-08-19T02:15:00Z',
        ip: '181.65.201.9',
      },
    },
    enrollments: [
      enrollment({
        id: 'enr_1190',
        status: 'under_review',
        seatStatus: 'reserved',
        paymentStatus: 'under_review',
        courseName: 'Francés Inicial',
        classGroupName: 'FR-I — Sáb 15:00',
        teacherName: 'Claire Dubois',
        planPriceId: 'pp_fr_i_v2',
        amountCents: 6490,
        paymentMethod: 'yape',
        operationNumber: null,
        createdAt: '2026-08-19T02:15:00Z',
        paidAt: null,
        progressPct: null,
      }),
    ],
    documents: [],
    documentRequests: [],
    attachments: [],
    activity: [
      audit({
        id: 'aud_51',
        action: 'payment_flagged',
        at: '2026-08-19T02:16:00Z',
        actorName: 'Sistema',
        actorRole: 'mass_approver',
        reference: { kind: 'review_flag', flag: 'illegible' },
      }),
    ],
  },
  {
    id: 'stu_0006',
    firstName: 'Diego',
    lastName: 'Huamán Ccopa',
    nationalIdType: 'DNI',
    nationalId: '71220456',
    email: 'diego.huaman@gmail.com',
    phone: '+51 918 442 771',
    birthDate: '2006-04-12',
    isMinor: false,
    status: 'active',
    country: 'PE',
    region: 'Cusco',
    city: 'Cusco',
    activeCourses: 1,
    totalEnrollments: 2,
    createdAt: '2026-01-22T16:10:00Z',
    lastActivityAt: '2026-08-16T19:44:00Z',
    guardian: null,
    enrollments: [
      enrollment({
        id: 'enr_1044',
        courseName: 'Inglés Intermedio B1',
        classGroupName: 'B1 — Mar/Jue 18:00',
        teacherName: 'Carlos Meza',
        planPriceId: 'pp_en_b1_v2',
        amountCents: 7990,
        operationNumber: '00733901',
        createdAt: '2026-07-11T12:30:00Z',
        paidAt: '2026-07-11T12:21:00Z',
        progressPct: 62,
      }),
      enrollment({
        id: 'enr_0880',
        status: 'completed',
        academicPeriodName: 'Ciclo 2026-I',
        createdAt: '2026-01-22T16:10:00Z',
        paidAt: '2026-01-22T16:02:00Z',
        operationNumber: '00318822',
        progressPct: 100,
      }),
    ],
    documents: [
      doc({
        id: 'doc_31',
        type: 'enrollment_certificate',
        enrollmentId: 'enr_1044',
        issuedAt: '2026-07-12T12:00:00Z',
        verificationCode: 'OOC-2026-S07VZ2',
        issuedByName: 'Lucía Ramírez',
        delivery: { status: 'queued', lastSentAt: null, attempts: 0 },
      }),
    ],
    documentRequests: [],
    attachments: [],
    activity: [
      audit({
        id: 'aud_61',
        action: 'payment_approved',
        at: '2026-07-11T12:34:00Z',
        actorName: 'Diego Salas',
        actorRole: 'treasury',
        reference: { kind: 'operation', number: '00733901' },
      }),
    ],
  },
  {
    id: 'stu_0007',
    firstName: 'Valentina',
    lastName: 'Núñez Ibarra',
    nationalIdType: 'DNI',
    nationalId: '74810223',
    email: 'valentina.nunez@gmail.com',
    phone: '+51 995 001 348',
    birthDate: '2009-12-05',
    isMinor: true,
    status: 'active',
    country: 'PE',
    region: 'Piura',
    city: 'Piura',
    activeCourses: 1,
    totalEnrollments: 1,
    createdAt: '2026-07-30T20:50:00Z',
    lastActivityAt: '2026-08-18T14:05:00Z',
    guardian: {
      firstName: 'Patricia',
      lastName: 'Ibarra León',
      relationship: 'mother',
      nationalIdType: 'DNI',
      nationalId: '43776512',
      email: 'patricia.ibarra@gmail.com',
      phone: '+51 995 001 300',
      consent: {
        version: 'v2026-01',
        acceptedAt: '2026-07-30T20:50:00Z',
        ip: '200.121.44.18',
      },
    },
    enrollments: [
      enrollment({
        id: 'enr_1150',
        courseName: 'Alemán Inicial',
        classGroupName: 'DE-I — Lun/Mié 19:00',
        teacherName: 'Katrin Wolf',
        planPriceId: 'pp_de_i_v1',
        amountCents: 6990,
        paymentMethod: 'plin',
        operationNumber: '61220874',
        createdAt: '2026-07-30T20:50:00Z',
        paidAt: '2026-07-30T20:41:00Z',
        progressPct: 20,
      }),
    ],
    documents: [],
    documentRequests: [],
    attachments: [],
    activity: [
      audit({
        id: 'aud_71',
        action: 'credentials_sent',
        at: '2026-07-30T20:58:00Z',
        actorName: 'Sistema',
        actorRole: 'coordinator',
        reference: null,
      }),
    ],
  },
  {
    id: 'stu_0008',
    firstName: 'Renzo',
    lastName: 'Palacios Vega',
    nationalIdType: 'passport',
    nationalId: 'PE4471902',
    email: 'renzo.palacios@gmail.com',
    phone: '+51 909 776 220',
    birthDate: '2001-07-19',
    isMinor: false,
    status: 'inactive',
    country: 'PE',
    region: 'Loreto',
    city: 'Iquitos',
    activeCourses: 0,
    totalEnrollments: 1,
    createdAt: '2026-04-02T11:00:00Z',
    lastActivityAt: '2026-04-09T11:00:00Z',
    guardian: null,
    enrollments: [
      enrollment({
        id: 'enr_1010',
        status: 'rejected',
        seatStatus: 'released',
        paymentStatus: 'rejected',
        courseName: 'Portugués Inicial',
        classGroupName: 'PT-I — Sáb 09:00',
        teacherName: 'Ana Beltrán',
        planPriceId: 'pp_pt_i_v2',
        amountCents: 5990,
        paymentMethod: 'yape',
        operationNumber: '00611233',
        createdAt: '2026-04-02T11:00:00Z',
        paidAt: null,
        progressPct: null,
      }),
    ],
    documents: [],
    documentRequests: [],
    attachments: [],
    activity: [
      audit({
        id: 'aud_81',
        action: 'payment_rejected',
        at: '2026-04-09T11:00:00Z',
        actorName: 'Diego Salas',
        actorRole: 'treasury',
        reference: { kind: 'operation', number: '00611233' },
      }),
    ],
  },
  ...pendingReceipts.map(pendingStudent),
]

export function listStudents(): StudentRow[] {
  return students.map(
    ({
      guardian,
      enrollments,
      documents,
      documentRequests,
      attachments,
      activity,
      ...row
    }) => {
      void guardian
      void enrollments
      void documents
      void documentRequests
      void attachments
      void activity
      return row
    },
  )
}

export function getStudent(id: string): StudentDetail | undefined {
  return students.find((s) => s.id === id)
}

export function getDashboardMetrics(): DashboardMetrics {
  return {
    enrollmentsToday: 148,
    enrollmentsTodayDelta: 12,
    pendingReview: listReviewQueue().length,
    oldestPendingHours: 6,
    activeStudents: 1284,
    activeStudentsDelta: 4,
    seatsTaken: 892,
    seatsCapacity: 1100,
  }
}

/** Receipts already sitting on a student file of their own. */
const flaggedReceipts: ReviewQueueItem[] = [
    {
      id: 'rev_01',
      studentId: 'stu_0002',
      studentName: 'Jhon Alexander Mamani Ccama',
      courseName: 'Inglés Básico A1',
      method: 'yape',
      amountCents: 6900,
      expectedAmountCents: 6990,
      operationNumber: '00993412',
      flag: 'amount_mismatch',
      tier: 2,
      confidence: 0.71,
      submittedAt: '2026-08-18T21:02:00Z',
    },
    {
      id: 'rev_02',
      studentId: 'stu_0005',
      studentName: 'Ana Lucía Chávez Soto',
      courseName: 'Francés Inicial',
      method: 'yape',
      amountCents: 6490,
      expectedAmountCents: 6490,
      // The extraction could not read the number — that is the flag itself.
      operationNumber: null,
      flag: 'illegible',
      tier: 3,
      confidence: 0.34,
      submittedAt: '2026-08-19T02:15:00Z',
    },
    {
      id: 'rev_03',
      studentId: 'stu_0006',
      studentName: 'Diego Huamán Ccopa',
      courseName: 'Inglés Intermedio B1',
      method: 'bcp',
      amountCents: 7990,
      expectedAmountCents: 7990,
      // Same number as an already approved payment — that is what pHash caught.
      operationNumber: '00733901',
      flag: 'duplicate_phash',
      tier: 0,
      confidence: 0.98,
      submittedAt: '2026-08-18T18:40:00Z',
    },
    {
      id: 'rev_04',
      studentId: 'stu_0007',
      studentName: 'Valentina Núñez Ibarra',
      courseName: 'Alemán Inicial',
      method: 'plin',
      amountCents: 6990,
      expectedAmountCents: 6990,
      operationNumber: '61220899',
      flag: 'model_divergence',
      tier: 2,
      confidence: 0.55,
      submittedAt: '2026-08-18T16:12:00Z',
    },
    {
      id: 'rev_05',
      studentId: 'stu_0003',
      studentName: 'Camila Torres Vílchez',
      courseName: 'Quechua Conversacional',
      method: 'interbank',
      amountCents: 5490,
      expectedAmountCents: 5490,
      operationNumber: '77120099',
      flag: 'low_confidence',
      tier: 2,
      confidence: 0.62,
      submittedAt: '2026-08-18T13:55:00Z',
    },
]

/**
 * The whole human queue, oldest first — the order it is worked in, and the one
 * the screen promises. Never a model's decision: tier 3 and divergence end
 * here by rule (CLAUDE.md §5).
 */
export function listReviewQueue(): ReviewQueueItem[] {
  return [
    ...flaggedReceipts,
    ...pendingReceipts.map(
      ({
        studentId,
        firstName,
        lastName,
        courseName,
        method,
        amountCents,
        expectedAmountCents,
        operationNumber,
        flag,
        tier,
        confidence,
        submittedAt,
        id,
      }): ReviewQueueItem => ({
        id,
        studentId,
        studentName: `${firstName} ${lastName}`,
        courseName,
        method,
        amountCents,
        expectedAmountCents,
        operationNumber,
        flag,
        tier,
        confidence,
        submittedAt,
      }),
    ),
  ].sort((a, b) => a.submittedAt.localeCompare(b.submittedAt))
}

/** Home preview: the five that have been waiting the longest. */
export function getReviewQueue(): ReviewQueueItem[] {
  return listReviewQueue().slice(0, 5)
}

export function getSeatWatch(): SeatWatchItem[] {
  return [
    {
      id: 'cg_01',
      courseName: 'Inglés Básico A1',
      classGroupName: 'A1 — Lun/Mié 18:00',
      startDate: '2026-09-07',
      seatsTaken: 38,
      capacity: 40,
    },
    {
      id: 'cg_02',
      courseName: 'Quechua Conversacional',
      classGroupName: 'QU-I — Sáb 11:00',
      startDate: '2026-09-12',
      seatsTaken: 29,
      capacity: 30,
    },
    {
      id: 'cg_03',
      courseName: 'Francés Inicial',
      classGroupName: 'FR-I — Sáb 15:00',
      startDate: '2026-09-12',
      seatsTaken: 18,
      capacity: 35,
    },
    {
      id: 'cg_04',
      courseName: 'Alemán Inicial',
      classGroupName: 'DE-I — Lun/Mié 19:00',
      startDate: '2026-09-07',
      seatsTaken: 9,
      capacity: 30,
    },
  ]
}

/* -------------------------------------------------------------------------- */
/* Class groups                                                                */
/* -------------------------------------------------------------------------- */

/** Language catalogue. New languages are rows here, never code branches. */
const LANGUAGES = {
  en: { id: 'lang_en', name: 'Inglés' },
  it: { id: 'lang_it', name: 'Italiano' },
  fr: { id: 'lang_fr', name: 'Francés' },
  de: { id: 'lang_de', name: 'Alemán' },
  qu: { id: 'lang_qu', name: 'Quechua' },
  pt: { id: 'lang_pt', name: 'Portugués' },
} as const

/**
 * Class groups across the three states that matter for the panel: still
 * enrolling, running, and finished — the last one being where certificates get
 * issued in batch. `certificateRule: 'exam_required'` marks Inglés Básico,
 * which certifies only after the student sits the certification exam
 * (`docs/REGRAS-NEGOCIO.md` §6), so it never goes out in a blind batch.
 */
const classGroups: ClassGroupDetail[] = [
  {
    id: 'cg_05',
    courseName: 'Italiano Inicial',
    code: 'ITA-0002',
    language: LANGUAGES.it,
    weekdays: ['tue', 'thu'],
    startTime: '19:00',
    teacherId: 'tea_03',
    teacherName: 'Paola Benítez',
    modality: 'online',
    academicPeriodName: 'Ciclo 2026-I',
    startDate: '2026-04-07',
    endDate: '2026-08-07',
    seatsTaken: 8,
    capacity: 30,
    status: 'finished',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 4,
    students: [
      {
        studentId: 'stu_0004',
        fullName: 'Sebastián Ríos Paredes',
        enrollmentId: 'enr_0712',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 18,
        gradeStatus: 'approved',
        certificationExam: null,
        certificateIssuedAt: '2026-01-20T14:00:00Z',
        delivery: { status: 'sent', lastSentAt: '2026-01-20T14:03:00Z', attempts: 1 },
        procedure: null,
      },
      {
        studentId: 'stu_0001',
        fullName: 'María Fernanda Quispe Ramos',
        enrollmentId: 'enr_0930',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 17,
        gradeStatus: 'approved',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0003',
        fullName: 'Camila Torres Vílchez',
        enrollmentId: 'enr_1120',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 15,
        gradeStatus: 'approved',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0006',
        fullName: 'Diego Huamán Ccopa',
        enrollmentId: 'enr_1044',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 14,
        gradeStatus: 'approved',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0008',
        fullName: 'Renzo Palacios Vega',
        enrollmentId: 'enr_0640',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 16,
        gradeStatus: 'approved',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0007',
        fullName: 'Valentina Núñez Ibarra',
        enrollmentId: 'enr_0655',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 12,
        gradeStatus: 'failed',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0005',
        fullName: 'Ana Lucía Chávez Soto',
        enrollmentId: 'enr_0661',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: null,
        gradeStatus: 'auto_failed',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0002',
        fullName: 'Jhon Alexander Mamani Ccama',
        enrollmentId: 'enr_0670',
        enrollmentStatus: 'active',
        paymentStatus: 'under_review',
        finalGrade: 16,
        gradeStatus: 'approved',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
    ],
  },
  {
    id: 'cg_06',
    courseName: 'Inglés Básico A1',
    code: 'ING-0004',
    language: LANGUAGES.en,
    weekdays: ['sat'],
    startTime: '09:00',
    teacherId: 'tea_01',
    teacherName: 'Carlos Meza',
    modality: 'online',
    academicPeriodName: 'Ciclo 2026-I',
    startDate: '2026-04-11',
    endDate: '2026-08-12',
    seatsTaken: 4,
    capacity: 40,
    status: 'finished',
    certificateRule: 'exam_required',
    allowsFreeze: true,
    allowsTransfer: true,
    pendingCertificates: 1,
    students: [
      {
        studentId: 'stu_0003',
        fullName: 'Camila Torres Vílchez',
        enrollmentId: 'enr_0801',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 18,
        gradeStatus: 'approved',
        certificationExam: 'approved',
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0006',
        fullName: 'Diego Huamán Ccopa',
        enrollmentId: 'enr_0802',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 17,
        gradeStatus: 'approved',
        certificationExam: 'pending',
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0007',
        fullName: 'Valentina Núñez Ibarra',
        enrollmentId: 'enr_0803',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: 15,
        gradeStatus: 'approved',
        certificationExam: 'not_requested',
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0008',
        fullName: 'Renzo Palacios Vega',
        enrollmentId: 'enr_0804',
        enrollmentStatus: 'completed',
        paymentStatus: 'approved',
        finalGrade: null,
        gradeStatus: 'pending',
        certificationExam: 'not_requested',
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
    ],
  },
  {
    id: 'cg_03',
    courseName: 'Francés Inicial',
    code: 'FRA-0003',
    language: LANGUAGES.fr,
    weekdays: ['sat'],
    startTime: '15:00',
    teacherId: 'tea_04',
    teacherName: 'Marion Lefèvre',
    modality: 'online',
    academicPeriodName: PERIOD,
    startDate: '2026-06-13',
    endDate: '2026-10-17',
    seatsTaken: 18,
    capacity: 35,
    status: 'in_progress',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [
      {
        studentId: 'stu_0003',
        fullName: 'Camila Torres Vílchez',
        enrollmentId: 'enr_1044',
        enrollmentStatus: 'active',
        paymentStatus: 'approved',
        finalGrade: null,
        gradeStatus: 'pending',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0005',
        fullName: 'Ana Lucía Chávez Soto',
        enrollmentId: 'enr_1051',
        enrollmentStatus: 'active',
        paymentStatus: 'approved',
        finalGrade: null,
        gradeStatus: 'pending',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
    ],
  },
  {
    id: 'cg_01',
    courseName: 'Inglés Básico A1',
    code: 'ING-0006',
    language: LANGUAGES.en,
    weekdays: ['mon', 'wed'],
    startTime: '18:00',
    teacherId: 'tea_01',
    teacherName: 'Carlos Meza',
    modality: 'online',
    academicPeriodName: PERIOD,
    startDate: '2026-09-07',
    endDate: '2027-01-13',
    seatsTaken: 38,
    capacity: 40,
    status: 'enrolling',
    certificateRule: 'exam_required',
    allowsFreeze: true,
    allowsTransfer: true,
    pendingCertificates: 0,
    students: [
      {
        studentId: 'stu_0001',
        fullName: 'María Fernanda Quispe Ramos',
        enrollmentId: 'enr_1188',
        enrollmentStatus: 'active',
        paymentStatus: 'approved',
        finalGrade: null,
        gradeStatus: 'pending',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0002',
        fullName: 'Jhon Alexander Mamani Ccama',
        enrollmentId: 'enr_1190',
        enrollmentStatus: 'active',
        paymentStatus: 'under_review',
        finalGrade: null,
        gradeStatus: 'pending',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0004',
        fullName: 'Sebastián Ríos Paredes',
        enrollmentId: 'enr_1193',
        enrollmentStatus: 'active',
        paymentStatus: 'approved',
        finalGrade: null,
        gradeStatus: 'pending',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
      {
        studentId: 'stu_0006',
        fullName: 'Diego Huamán Ccopa',
        enrollmentId: 'enr_1201',
        enrollmentStatus: 'under_review',
        paymentStatus: 'under_review',
        finalGrade: null,
        gradeStatus: 'pending',
        certificationExam: null,
        certificateIssuedAt: null,
        delivery: null,
        procedure: null,
      },
    ],
  },
  {
    id: 'cg_02',
    courseName: 'Quechua Conversacional',
    code: 'QUE-0003',
    language: LANGUAGES.qu,
    weekdays: ['sat'],
    startTime: '11:00',
    teacherId: 'tea_05',
    teacherName: 'Rosa Ccahuana',
    modality: 'online',
    academicPeriodName: PERIOD,
    startDate: '2026-09-12',
    endDate: '2026-12-19',
    seatsTaken: 29,
    capacity: 30,
    status: 'enrolling',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_04',
    courseName: 'Alemán Inicial',
    code: 'ALE-0002',
    language: LANGUAGES.de,
    weekdays: ['mon', 'wed'],
    startTime: '19:00',
    teacherId: 'tea_06',
    teacherName: 'Klaus Brenner',
    modality: 'online',
    academicPeriodName: PERIOD,
    startDate: '2026-09-07',
    endDate: '2027-01-11',
    seatsTaken: 9,
    capacity: 30,
    status: 'enrolling',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_07',
    courseName: 'Inglés Intermedio B1',
    code: 'ING-0005',
    language: LANGUAGES.en,
    weekdays: ['tue', 'thu'],
    startTime: '20:00',
    teacherId: 'tea_02',
    teacherName: 'Andrea Solís',
    modality: 'online',
    academicPeriodName: PERIOD,
    startDate: '2026-07-14',
    endDate: '2026-09-17',
    seatsTaken: 24,
    capacity: 25,
    status: 'in_progress',
    certificateRule: 'automatic',
    allowsFreeze: false,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_08',
    courseName: 'Portugués Inicial',
    code: 'POR-0002',
    language: LANGUAGES.pt,
    weekdays: ['sat'],
    startTime: '09:00',
    teacherId: 'tea_07',
    teacherName: 'Bruno Antunes',
    modality: 'online',
    academicPeriodName: PERIOD,
    startDate: '2026-09-12',
    endDate: '2026-12-19',
    seatsTaken: 12,
    capacity: 30,
    status: 'enrolling',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_09',
    courseName: 'Inglés Básico A1',
    code: 'ING-0007',
    language: LANGUAGES.en,
    weekdays: ['sat'],
    startTime: '15:00',
    teacherId: 'tea_02',
    teacherName: 'Andrea Solís',
    modality: 'online',
    academicPeriodName: PERIOD,
    startDate: '2026-09-12',
    endDate: '2027-01-16',
    seatsTaken: 31,
    capacity: 40,
    status: 'enrolling',
    certificateRule: 'exam_required',
    allowsFreeze: true,
    allowsTransfer: true,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_10',
    courseName: 'Italiano Inicial',
    code: 'ITA-0003',
    language: LANGUAGES.it,
    weekdays: ['mon', 'wed'],
    startTime: '20:00',
    teacherId: 'tea_03',
    teacherName: 'Paola Benítez',
    modality: 'online',
    academicPeriodName: PERIOD,
    startDate: '2026-09-07',
    endDate: '2027-01-11',
    seatsTaken: 6,
    capacity: 30,
    status: 'enrolling',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_11',
    courseName: 'Quechua Conversacional',
    code: 'QUE-0002',
    language: LANGUAGES.qu,
    weekdays: ['tue'],
    startTime: '18:00',
    teacherId: 'tea_05',
    teacherName: 'Rosa Ccahuana',
    modality: 'online',
    academicPeriodName: 'Ciclo 2026-I',
    startDate: '2026-03-10',
    endDate: '2026-06-30',
    seatsTaken: 22,
    capacity: 25,
    status: 'closed',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_12',
    courseName: 'Inglés Básico A1',
    code: 'ING-0002',
    language: LANGUAGES.en,
    weekdays: ['mon', 'wed'],
    startTime: '18:00',
    teacherId: 'tea_01',
    teacherName: 'Carlos Meza',
    modality: 'online',
    academicPeriodName: 'Ciclo 2026-I',
    startDate: '2026-03-09',
    endDate: '2026-07-13',
    seatsTaken: 37,
    capacity: 40,
    status: 'closed',
    certificateRule: 'exam_required',
    allowsFreeze: true,
    allowsTransfer: true,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_13',
    courseName: 'Inglés Intermedio B1',
    code: 'ING-0003',
    language: LANGUAGES.en,
    weekdays: ['tue', 'thu'],
    startTime: '20:00',
    teacherId: 'tea_02',
    teacherName: 'Andrea Solís',
    modality: 'online',
    academicPeriodName: 'Ciclo 2026-I',
    startDate: '2026-03-10',
    endDate: '2026-06-25',
    seatsTaken: 23,
    capacity: 25,
    status: 'closed',
    certificateRule: 'automatic',
    allowsFreeze: false,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_14',
    courseName: 'Francés Inicial',
    code: 'FRA-0002',
    language: LANGUAGES.fr,
    weekdays: ['sat'],
    startTime: '15:00',
    teacherId: 'tea_04',
    teacherName: 'Marion Lefèvre',
    modality: 'online',
    academicPeriodName: 'Ciclo 2026-I',
    startDate: '2026-03-14',
    endDate: '2026-07-18',
    seatsTaken: 26,
    capacity: 35,
    status: 'closed',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_15',
    courseName: 'Alemán Inicial',
    code: 'ALE-0001',
    language: LANGUAGES.de,
    weekdays: ['mon', 'wed'],
    startTime: '19:00',
    teacherId: 'tea_06',
    teacherName: 'Klaus Brenner',
    modality: 'online',
    academicPeriodName: 'Ciclo 2026-I',
    startDate: '2026-03-09',
    endDate: '2026-07-15',
    seatsTaken: 19,
    capacity: 30,
    status: 'closed',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_16',
    courseName: 'Portugués Inicial',
    code: 'POR-0001',
    language: LANGUAGES.pt,
    weekdays: ['sat'],
    startTime: '09:00',
    teacherId: 'tea_07',
    teacherName: 'Bruno Antunes',
    modality: 'online',
    academicPeriodName: 'Ciclo 2026-I',
    startDate: '2026-03-14',
    endDate: '2026-06-27',
    seatsTaken: 24,
    capacity: 30,
    status: 'closed',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_17',
    courseName: 'Inglés Básico A1',
    code: 'ING-0001',
    language: LANGUAGES.en,
    weekdays: ['sat'],
    startTime: '09:00',
    teacherId: 'tea_02',
    teacherName: 'Andrea Solís',
    modality: 'online',
    academicPeriodName: 'Ciclo 2025-II',
    startDate: '2025-09-13',
    endDate: '2026-01-17',
    seatsTaken: 39,
    capacity: 40,
    status: 'closed',
    certificateRule: 'exam_required',
    allowsFreeze: true,
    allowsTransfer: true,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_18',
    courseName: 'Italiano Inicial',
    code: 'ITA-0001',
    language: LANGUAGES.it,
    weekdays: ['mon', 'wed'],
    startTime: '20:00',
    teacherId: 'tea_03',
    teacherName: 'Paola Benítez',
    modality: 'online',
    academicPeriodName: 'Ciclo 2025-II',
    startDate: '2025-09-08',
    endDate: '2026-01-12',
    seatsTaken: 21,
    capacity: 30,
    status: 'closed',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_19',
    courseName: 'Quechua Conversacional',
    code: 'QUE-0001',
    language: LANGUAGES.qu,
    weekdays: ['sat'],
    startTime: '11:00',
    teacherId: 'tea_05',
    teacherName: 'Rosa Ccahuana',
    modality: 'online',
    academicPeriodName: 'Ciclo 2025-II',
    startDate: '2025-09-13',
    endDate: '2025-12-20',
    seatsTaken: 28,
    capacity: 30,
    status: 'closed',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
  {
    id: 'cg_20',
    courseName: 'Francés Inicial',
    code: 'FRA-0001',
    language: LANGUAGES.fr,
    weekdays: ['tue', 'thu'],
    startTime: '19:00',
    teacherId: 'tea_04',
    teacherName: 'Marion Lefèvre',
    modality: 'online',
    academicPeriodName: 'Ciclo 2025-II',
    startDate: '2025-09-09',
    endDate: '2026-01-15',
    seatsTaken: 30,
    capacity: 35,
    status: 'closed',
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    pendingCertificates: 0,
    students: [],
  },
]

/**
 * The course catalog. Hours and module counts come from
 * `docs/REGRAS-NEGOCIO.md` §3 where the source states them (Inglés Básico: 4
 * modules, 20h each) and are plausible fill-ins elsewhere — the real numbers
 * are catalog data the Asociación owns, not something to derive in code.
 *
 * `minAge` follows §2: 13 for every language except the Inglés kids track,
 * which does not exist in this mock.
 */
const courses: CourseRow[] = [
  {
    id: 'crs_01',
    name: 'Inglés Básico A1',
    language: LANGUAGES.en,
    level: 'A1',
    minAge: 13,
    modules: 4,
    totalHours: 80,
    certificateRule: 'exam_required',
    allowsFreeze: true,
    allowsTransfer: true,
    active: true,
    classGroupCount: 0,
  },
  {
    id: 'crs_02',
    name: 'Inglés Intermedio B1',
    language: LANGUAGES.en,
    level: 'B1',
    minAge: 13,
    modules: 2,
    totalHours: 80,
    certificateRule: 'automatic',
    // §2 and §5: the intermediate/advanced track cannot be frozen.
    allowsFreeze: false,
    allowsTransfer: false,
    active: true,
    classGroupCount: 0,
  },
  {
    id: 'crs_03',
    name: 'Francés Inicial',
    language: LANGUAGES.fr,
    level: 'Inicial',
    minAge: 13,
    modules: 4,
    totalHours: 80,
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    active: true,
    classGroupCount: 0,
  },
  {
    id: 'crs_04',
    name: 'Alemán Inicial',
    language: LANGUAGES.de,
    level: 'Inicial',
    minAge: 13,
    modules: 4,
    totalHours: 80,
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    active: true,
    classGroupCount: 0,
  },
  {
    id: 'crs_05',
    name: 'Italiano Inicial',
    language: LANGUAGES.it,
    level: 'Inicial',
    minAge: 13,
    modules: 4,
    totalHours: 80,
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    active: true,
    classGroupCount: 0,
  },
  {
    id: 'crs_06',
    name: 'Portugués Inicial',
    language: LANGUAGES.pt,
    level: 'Inicial',
    minAge: 13,
    modules: 4,
    totalHours: 80,
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    active: true,
    classGroupCount: 0,
  },
  {
    id: 'crs_07',
    name: 'Quechua Conversacional',
    language: LANGUAGES.qu,
    level: 'Inicial',
    minAge: 13,
    modules: 3,
    totalHours: 60,
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    active: true,
    classGroupCount: 0,
  },
  {
    id: 'crs_08',
    name: 'Chino Mandarín Básico',
    language: { id: 'lang_zh', name: 'Chino Mandarín' },
    level: 'Inicial',
    minAge: 13,
    modules: 3,
    totalHours: 60,
    certificateRule: 'automatic',
    allowsFreeze: true,
    allowsTransfer: false,
    // In the catalog but with no class group open this period.
    active: false,
    classGroupCount: 0,
  },
]

/** Class group count is derived, never stored — it would drift the moment one opens. */
export function listCourses(): CourseRow[] {
  return courses
    .map((course) => ({
      ...course,
      classGroupCount: classGroups.filter((group) => group.courseName === course.name)
        .length,
    }))
    .sort(
      (a, b) =>
        a.language.name.localeCompare(b.language.name) || a.name.localeCompare(b.name),
    )
}

export function listClassGroups(): ClassGroupRow[] {
  return classGroups.map(({ students, ...row }) => {
    void students
    return row
  })
}

export function getClassGroup(id: string): ClassGroupDetail | undefined {
  return classGroups.find((group) => group.id === id)
}
