import type { ReceiptUpload } from "./ReceiptUpload.js";

/**
 * File custody rows for checkout receipts. Every transition is guarded on
 * the row's current status in the same way `ISeatHoldRepository`'s are — a
 * confirm that arrives twice, or a normalize job redelivered by the queue,
 * finds nothing left to change instead of overwriting a later state.
 */
export interface IReceiptUploadRepository {
  /** Mints the row a fresh upload target is issued for — always `pending`.
   * `id` is generated by the caller (`RequestReceiptUploadUseCase`), not the
   * database: the object key embeds it, so it has to exist before the row
   * does. */
  create(params: { id: string; seatHoldId: string; objectKey: string; contentType: string }): Promise<ReceiptUpload>;

  /** The row as recorded, whatever its status. `null` when the id is
   * unknown — the caller treats that the same as "not found", never as
   * "not yours" (CLAUDE.md §8, anti-IDOR: no id from the client is trusted
   * enough to distinguish the two). */
  findById(id: string): Promise<ReceiptUpload | null>;

  /** `pending → uploaded`, once the object is confirmed to exist in the
   * bucket. `null` if the row was not `pending` any more — a second confirm
   * is a no-op, not a second write. */
  markUploaded(id: string, params: { contentType: string; byteSize: number }): Promise<ReceiptUpload | null>;
}
